CREATE TABLE Users (
userId INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(50),
address VARCHAR(255));

CREATE TABLE Accounts (
accountId INTEGER PRIMARY KEY AUTOINCREMENT,
userId INTEGER(10),
balance INTEGER(15),
currency VARCHAR(10),
FOREIGN KEY (userId)  REFERENCES Users (userId));

CREATE TABLE Transactions (
transactionId INTEGER PRIMARY KEY AUTOINCREMENT,
accountId INTEGER(10),
amount DECIMAL(15),
FOREIGN KEY (accountId)  REFERENCES Accounts (accountId));